SwedenRun/SwedenRun/Models/FakeSweRunRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SwedenRun.Models
{
  public class FakeSweRunRepository : ISweRunRepository
  {

    /**
     *  RUNNER
     */
    public IQueryable<Runner> Runners => new List<Runner>
    {
      new Runner { RunnerId = "R001", Age = "27", Email = "alex@strand.com", Name = "Alexander Strand" },
      new Runner { RunnerId = "R002", Age = "55", Name = "Batman"},
      new Runner { RunnerId = "R003", Name = "Elon Musk"}
    }.AsQueryable<Runner>();

    public Runner GetRunnerDetails(string id)
    {
      return Runners.Where(runner => runner.RunnerId.Equals(id)).First();
    }

    public bool SaveRunner(Runner runner)
    {
      //If runner does not exists, add to database
      if(!(Runners.Any(r => r.RunnerId == runner.RunnerId)))
      {
        //Runners.Add(runner);
      }
      return true;
    }

    /**
     *  RUN
     */
    public IQueryable<Run> Runs => new List<Run>
    {
      new Run{ RunId = 1, RunnerId = "R001", Distance = 10, Time = "55:00", Date="2021-01-01"},
      new Run{ RunId = 2, RunnerId = "R001", Distance = 5.5, Time = "25:20", Date="2021-01-03"},
      new Run{ RunId = 3, RunnerId = "R001", Distance = 10, Time = "52:00", Date="2021-01-02"},
      new Run{ RunId = 4, RunnerId = "R002", Distance = 3, Time = "30:00", Date="2021-01-10"},
      new Run{ RunId = 5, RunnerId = "R002", Distance = 5, Time = "45:00", Date="2021-01-07"},
      new Run{ RunId = 6, RunnerId = "R003", Distance = 12, Time = "55:00", Date="2021-01-01"}
    }.AsQueryable<Run>();

    public IQueryable<Run> GetRunnerRuns(string id)
    {
      var runs = from run in Runs
                 where run.RunnerId.Equals(id)
                 select run;
      return runs;
    }
  }
}

SwedenRun/SwedenRun/Models/ISweRunRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SwedenRun.Models
{
  public interface ISweRunRepository
  {
    IQueryable<Runner> Runners { get; }
    Runner GetRunnerDetails(string id);
    bool SaveRunner(Runner runner);
    IQueryable<Run> Runs { get; }
    IQueryable<Run> GetRunnerRuns(string id);
  }
}

SwedenRun/SwedenRun/Models/POCO/ISweRunRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SwedenRun.Models
{
  public interface ISweRunRepository
  {
    IQueryable<Runner> Runners { get; }
  }
}

SwedenRun/SwedenRun/Models/POCO/Run.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SwedenRun.Models
{
  public class Run
  {
    public int RunId { set; get; }
    public string Date { set; get; }

    public double Distance { set; get; }
    public string Time { set; get; }

    public string RunnerId { set; get; }
  }
}

SwedenRun/SwedenRun/Models/POCO/Runner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SwedenRun.Models
{
  public class Runner
  {
    public string RunnerId { set; get; }

    [Display(Name = "Name")]
    [Required(ErrorMessage = "The Name field is required.")]
    public string Name { set; get; }

    [Display(Name = "Email", Prompt = "name@example.com")]
    [Required(ErrorMessage = "The Email field is required.")]
    public string Email { set; get; }

    [Display(Name = "Age", Prompt = "Select")]
    public string Age { set; get; }

  }
}

SwedenRun/SwedenRun/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SwedenRun.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SwedenRun.Controllers
{
  public class HomeController : Controller
  {
    public ViewResult Index()
    {
      return View();
    }

    public ViewResult Index1(Runner runner)
    {
      return View(runner);
    }
  }
}

SwedenRun/SwedenRun/Controllers/RunnerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SwedenRun.Models;

namespace SwedenRun.Controllers
{
  public class RunnerController : Controller
  {
    private ISweRunRepository repository;

    public RunnerController(ISweRunRepository repo)
    {
      repository = repo;
    }

    public ViewResult AddRunner()
    {
      return View();
    }

    public ViewResult AllRunners()
    {
      return View(repository.Runners);
    }

    public ViewResult RunnerDetail(string id)
    {
      ViewBag.RunList = repository.GetRunnerRuns(id);

      return View(repository.GetRunnerDetails(id));
    }
  }
}

SwedenRun/SwedenRun/Views/Home/AllRunners.cshtml
@{
  ViewBag.Title = "All Runners - Sweden Run";
}

@model IEnumerable<Runner>

<h3 class="text-muted text-center">All runners!</h3>
<div class="wrapper">
  <table class="table table-striped table-hover" >
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Total Distance</th>
      </tr>
    </thead>
    <tbody>
      @foreach (Runner runner in @Model)
      {
        <tr>
          <th scope="row"><img src="~/images/Runner.png" alt="Runner avatar" width="50" height="50"></th>
          <td>@runner.RunnerId</td>
          <td>@runner.Name</td>
          <td>200 km</td>
        </tr>
      }
    </tbody>
  </table>
</div>

SwedenRun/SwedenRun/Views/Home/Index.cshtml
@{
  ViewBag.Title = "Home - Sweden Runner";
}

<!-- Page Content -->
<div class="container">
  <div class="row start">
      <h1 class="fw-light">Sweden Run</h1>

      <p class="lead">Sign in</p>

      <div class="form-sigin">
        <div class="container d-flex flex-column justify-content-center align-items-center">
          <form>
            <label for="input-email" class="visually-hidden">Email address</label>
            <input type="email" id="input-email" class="form-control" placeholder="Email address" required autofocus>
            <label for="input-password" class="visually-hidden">Password</label>
            <input type="password" id="input-password" class="form-control" placeholder="Password" required>

            <button class="w-75 mt-2 btn btn-primary" type="submit">Sign in</button>
            <hr style="margin: 0.5em" />

            <a class="w-75 btn btn-secondary" asp-controller="Runner" asp-action="AddRunner">Create Runner</a>
          </form>
        </div>
    </div>
  </div>
</div>

SwedenRun/SwedenRun/Views/Home/Index1.cshtml
@model Runner 

<h1>@Model.Name</h1>
<p>Age - @Model.Age</p>
<p>Email - @Model.Email</p>
<p>Id - @Model.RunnerId</p>

SwedenRun/SwedenRun/Views/Runner/AddRunner.cshtml
@{
  ViewBag.Title = "Add Runner - Sweden Runner";
}

@model Runner

<div class="container">
  <div class="py-5 text-center">
    <h2>Create your Runner!</h2>
    <p class="lead">Add your personal information to start your journey of running across Sweden!</p>
    <p class="small text-muted">Personal data will only be stored for the use of this application</p>
  </div>

  <div class="row g-3">
    <!--Right Section-->
    <div class="col-md-5 col-lg-4 order-md-last">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">PLACEHOLDER</span>
        <span class="text-muted">Status</span>
      </h4>
    </div>

    <!--Left Section-->
    <div class="col-md-7 col-lg-8">
      <h4 class="mb-3">Runner Information</h4>

      <form class="needs-validation" asp-controller="Home" asp-action="Index1" method="post">
        <!--<form class="needs-validation" novalidate>-->
        <div class="row g-3">
          <div class="col-12">
            <label class="form-label" asp-for="Name"></label>
            <input type="text" class="form-control" asp-for="Name">
          </div>

          <div class="col-12">
            <label class="form-label" asp-for="Email"></label>
            <input type="email" class="form-control" asp-for="Email">
          </div>

          <div class="col-12">
            <label class="form-label" asp-for="Age"></label>
            <select class="form-select" asp-for="Age">
              <option value="">Select</option>
              @for (int i = 0; i <= 100; i++)
              {
                <option value="@i">@i years</option>
              }
            </select>
          </div>

          <div class="col-12">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password">
          </div>

          <div class="col-12">
            <label for="confirm-password" class="form-label">Confirm password</label>
            <input type="password" class="form-control" id="confirm-password">
          </div>
        </div>
        <hr class="my-4">
        <div asp-validation-summary="All" style="color:red;"></div>

        <input class="w-100 btn btn-primary btn-lg" type="submit" value="Create Runner" />
        <!--<button class="w-100 btn btn-primary btn-lg" type="submit">Create runner</button>-->
      </form>
    </div>
  </div>
</div>

SwedenRun/SwedenRun/Views/Runner/AllRunners.cshtml
@{
  ViewBag.Title = "All Runners - Sweden Run";
}

@model IEnumerable<Runner>

<h3 class="text-muted text-center">All runners!</h3>
<div class="wrapper">
  <table class="table table-striped table-hover" >
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Total Distance</th>
      </tr>
    </thead>
    <tbody>
      @foreach (Runner runner in @Model)
      {
        <tr>
          <th scope="row"><img src="~/images/Runner.png" alt="Runner avatar" width="50" height="50"></th>
          <td><a asp-controller="Runner" asp-action="RunnerDetail" asp-route-id="@runner.RunnerId">@runner.RunnerId</a></td>
          <td>@runner.Name</td>
          <td>200 km</td>
        </tr>
      }
    </tbody>
  </table>
</div>

SwedenRun/SwedenRun/Views/Runner/RunnerDetail.cshtml
@{
  ViewBag.Title = "Runner - Sweden Run";
}

@model Runner

<div class="container">
  <div class="py-5 text-center">
    <h2>@Model.Name's Runner Page</h2>
    <p class="lead">Check out @Model.Name's amazing progress!</p>
  </div>

  <div class="row g-3">
    <!--Right Section-->
    <div class="col-md-6 col-lg-5 order-md-last">
      <div class="card">
        <div class="card-header">
          Runner progress
        </div>
        <div class="card-body">
          <p class="card-text">Total distance run: </p>
        </div>
      </div>
      <p>Progress across Sweden</p>
      <div class="progress">
        <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
      </div>

    </div>

    <!--Left Section-->
    <div class="col-md-6 col-lg-7">
      <h4 class="mb-3">Runner Information</h4>
      <div class="card" id="run-list">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th scope="col">Distance</th>
              <th scope="col">Time</th>
              <th scope="col">Date</th>
            </tr>
          </thead>
          <tbody>
            @foreach (Run run in ViewBag.RunList)
            {
              <tr>
                <td>@run.Distance</td>
                <td>@run.Time</td>
                <td>@run.Date</td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

SwedenRun/SwedenRun/Views/Shared/_BasicLayout.cshtml
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="~/css/style.css" />

  <!--Bootstrap-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
  <title>@ViewBag.Title</title>

</head>

<body>

  <!--Header-->
  <nav class="header navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" asp-controller="Home" asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694L1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z" />
          <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z" />
        </svg>
        Sweden Run
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" asp-controller="Runner" asp-action="AllRunners">Runners</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Run</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!--Main body-->
  <div>
    @RenderBody()
  </div>

  <!--Footer-->
  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">Developed by Alexander Strand </p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>

  <!--Bootstrap-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</body>
</html>